updated the seminar and bio for Pete and Mozhgan
RSE-Sheffield/old_team_site_nikola pull request #94
Opened 2018-08-20 08:56 UTC by mozhgan-kch

2018-08-20 09:05 UTC, willfurnass commented on site/files/seminar_files/bio/david_hubber.md
> +David Hubber is an astrophysicist by training that has worked extensively on writing software such as GANDALF and SEREN to simulate star forming regions. He has been a researcher at the university of
Links to GANDALF and SEREN?  Links to his own website / profile page / twitter?

2018-08-20 09:06 UTC, willfurnass commented on site/files/seminar_files/bio/joz_martin.md
> +Jos Martin is the senior engineering manager for parallel computing products at MathWorks. He has responsibility for all parts of Parallel Computing Toolbox, including the use of GPU and big data typ
NB typo in Markdown file name or in the name in this para?  Links to MATLAB products he's responsible for?

2018-08-20 09:07 UTC, willfurnass commented on site/pages/community/seminars.md
>  <strong>Rob Baxter (EPCC)</strong><br/><br/>
Link to bio?

2018-08-20 09:41 UTC, willfurnass commented on site/pages/community/seminars.md
> +<strong>David Hubber, Researcher at Ludwig-Maximilians-Universität Munich<a href="/seminar_files/bio/david_hubber.md" target="popup" onclick="window.open('/seminar_files/bio/david_hubber.md','name','
Pop-up doesn't work.  Simpler/cleaner to just include the bio below the abstract?

2018-08-20 09:42 UTC, willfurnass commented on site/pages/community/seminars.md
> +<strong>Joz Martin (Mathworks) <a href="/seminar_files/bio/joz_martin.md" target="popup" onclick="window.open('/seminar_files/bio/joz_martin.md','name','width=600,height=400')">(Bio)</a></strong><br/
Pop-up doesn't work.  Simpler/cleaner to just include the bio below the abstract?

2018-08-20 09:43 UTC, willfurnass requested changes
See comments in-line

2018-08-20 10:39 UTC, willfurnass commented on site/pages/community/seminars.md
> +### September 12, 2018 &mdash; 15:30-16:30, Hicks building, Lecture theatre 7
Probably want a capital T too

2018-08-20 10:39 UTC, mozhgan-kch commented on site/files/seminar_files/bio/david_hubber.md
> +David Hubber is an astrophysicist by training that has worked extensively on writing software such as GANDALF and SEREN to simulate star forming regions. He has been a researcher at the university of
info is not available

2018-08-20 10:40 UTC, mozhgan-kch commented on site/files/seminar_files/bio/joz_martin.md
> +Jos Martin is the senior engineering manager for parallel computing products at MathWorks. He has responsibility for all parts of Parallel Computing Toolbox, including the use of GPU and big data typ
info is not available

2018-08-20 10:44 UTC, mozhgan-kch commented on site/pages/community/seminars.md
> +### September 12, 2018 &mdash; 15:30-16:30, Hicks building, Lecture theatre 7
Done

2018-08-20 11:16 UTC, willfurnass commented on site/pages/community/seminars.md
> +<strong>Dr Patricio Ortiz, Newcastle University</strong><br/><br/>
Sheffield University

2018-08-20 11:16 UTC, willfurnass commented on site/pages/community/seminars.md
> +<strong>Dr Patricio Ortiz, Newcastle University</strong><br/><br/>
Author name + affilliation not consistently formatted throughout page.

2018-08-20 11:43 UTC, willfurnass commented on site/files/seminar_files/bio/david_hubber.md
> +David Hubber is an astrophysicist by training that has worked extensively on writing software such as GANDALF and SEREN to simulate star forming regions. He has been a researcher at the university of
File no longer needed?

2018-08-20 11:43 UTC, willfurnass commented on site/files/seminar_files/bio/joz_martin.md
> +Jos Martin is the senior engineering manager for parallel computing products at MathWorks. He has responsibility for all parts of Parallel Computing Toolbox, including the use of GPU and big data typ
File no longer needed?

2018-08-20 11:44 UTC, willfurnass commented on site/pages/community/seminars.md
>  <strong>Rob Baxter (EPCC)</strong><br/><br/>
No bio

2018-08-20 11:44 UTC, willfurnass requested changes
See new in-line comments.

2018-09-05 09:54 UTC, mozhgan-kch commented on site/files/seminar_files/bio/joz_martin.md
> +Jos Martin is the senior engineering manager for parallel computing products at MathWorks. He has responsibility for all parts of Parallel Computing Toolbox, including the use of GPU and big data typ
No

2018-09-05 09:54 UTC, mozhgan-kch commented on site/files/seminar_files/bio/david_hubber.md
> +David Hubber is an astrophysicist by training that has worked extensively on writing software such as GANDALF and SEREN to simulate star forming regions. He has been a researcher at the university of
no

2018-09-06 10:02 UTC, merged