Added Osteolytica project wrapup blog post
RSE-Sheffield/old_team_site_nikola pull request #99
Opened 2018-09-17 16:37 UTC by twinkarma

2018-09-26 09:58 UTC, willfurnass commented
@twinkarma CI could not build this:
```
..[2018-09-17T16:39:25Z] ERROR: Nikola: Two posts are trying to generate blog/2nd-gpu-seminar-amr/index.html: posts/2017_05_30_gpu-computing-seminar-adaptive-mesh-refinement.md and posts/2018_09_17_osteolytica-project-wrapup.md
[2018-09-17T16:39:25Z] ERROR: Nikola: Two posts are trying to generate blog/2nd-gpu-seminar-amr/index.md: posts/2017_05_30_gpu-computing-seminar-adaptive-mesh-refinement.md and posts/2018_09_17_osteolytica-project-wrapup.md
```

2018-10-03 16:17 UTC, twinkarma commented
I've fixed the issue now and have also added current & previous DL training events.

2018-10-04 09:33 UTC, willfurnass requested changes

2018-10-04 09:33 UTC, willfurnass commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +While theoretically it should be possible to compare the bone volumes over time period directly, there’s a problem where bone volumes in each scan do not align to each other exactly. The alignment pr
Add links to 'COBYLA' and 'nlopt'?

2018-10-04 09:33 UTC, willfurnass commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +**Figure 1:** The expansion process shown in 2D. a) Bone volume is shown in black. b) The volume is expanded (red) until all the gaps are enclosed. c) Once the expansion is completed, the inside volu
On my display figure captions start to the R of the image(s) then wrap around beneath them.  Better to have a blank link in the markdown between the image and caption so the caption is treated as a separate  paragraph?

2018-10-04 09:33 UTC, willfurnass commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +While theoretically it should be possible to compare the bone volumes over time period directly, there’s a problem where bone volumes in each scan do not align to each other exactly. The alignment pr
Any code publicly available?  Want to add anything re the experience of working with academics / designing the UI?

2018-10-04 09:34 UTC, willfurnass commented
Also, in future it's better to submit multiple PRs for e.g. new blog post and new training info.  Makes the review process simpler.

2018-10-04 10:10 UTC, willfurnass commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +.. date: 2018-09-17 14:00:00 UTC+01:00
Bump date so appears as most recent blog post.

2018-10-04 11:24 UTC, twinkarma commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +While theoretically it should be possible to compare the bone volumes over time period directly, there’s a problem where bone volumes in each scan do not align to each other exactly. The alignment pr
Added link in revision

2018-10-04 11:25 UTC, twinkarma commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +**Figure 1:** The expansion process shown in 2D. a) Bone volume is shown in black. b) The volume is expanded (red) until all the gaps are enclosed. c) Once the expansion is completed, the inside volu
Fixed in revision

2018-10-04 11:26 UTC, twinkarma commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +While theoretically it should be possible to compare the bone volumes over time period directly, there’s a problem where bone volumes in each scan do not align to each other exactly. The alignment pr
No publicly available code as it's meant to be a commercial product in the future. I'll do another post  once we have the clinical data and we get to test the program on more samples.

2018-10-04 11:27 UTC, twinkarma commented on site/posts/2018_09_17_osteolytica-project-wrapup.md
> +.. date: 2018-09-17 14:00:00 UTC+01:00
Done

2018-10-04 11:28 UTC, twinkarma commented
Sorry about the stacked PRs, I'll make sure to put the separate changes on different branches next time.

2018-10-04 11:40 UTC, merged